AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Quiz Engine Backend

Globals:
  Function:
    Timeout: 10
    Runtime: python3.9
    MemorySize: 128
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Events:
        PostQuiz:
          Type: Api
          Properties:
            Path: /hello
            Method: post
        GetStatus:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        GetQuestions:
          Type: Api
          Properties:
            Path: /questions
            Method: get